"""articles table

Revision ID: 6d532bab951f
Revises: e8957e35244f
Create Date: 2021-04-24 10:12:58.484585

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d532bab951f'
down_revision = 'e8957e35244f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('title', sa.String(length=256), nullable=True),
    sa.Column('subtitle', sa.String(length=256), nullable=True),
    sa.Column('summary', sa.String(length=1028), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('url', sa.String(length=64), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_article_subtitle'), 'article', ['subtitle'], unique=True)
    op.create_index(op.f('ix_article_summary'), 'article', ['summary'], unique=True)
    op.create_index(op.f('ix_article_timestamp'), 'article', ['timestamp'], unique=False)
    op.create_index(op.f('ix_article_title'), 'article', ['title'], unique=True)
    op.create_index(op.f('ix_article_url'), 'article', ['url'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_article_url'), table_name='article')
    op.drop_index(op.f('ix_article_title'), table_name='article')
    op.drop_index(op.f('ix_article_timestamp'), table_name='article')
    op.drop_index(op.f('ix_article_summary'), table_name='article')
    op.drop_index(op.f('ix_article_subtitle'), table_name='article')
    op.drop_table('article')
    # ### end Alembic commands ###
